# 100 Numpy Exercises

1. Import the numpy package under the name np¶
numpy 패키지를 np 이름으로 사용

In [22]:
import numpy as np

2. Print the numpy version and the configuration¶
numpy 버전 및 설정 확인

In [5]:
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/nagap/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/nagap/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/nagap/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/nagap/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/nagap/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/nagap/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/nagap/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/nagap/anaconda3\\Library\\include']


3. Create a null vector of size 10¶
10개의 0으로 채워진 null vector 생성

In [11]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array¶
배열의 메모리 크기 확인

In [14]:
# itemsize = 배열의 전체요소가 차지하는 byte크기
# size = 배열의 전체 요소의 개수
# 메모리 크기: 요소의 전체수 * 전체요소의 byte크기 

z = np.zeros((10,10))
print(z.size, z.itemsize)
print("%d bytes" %(z.size * z.itemsize))

100 8
800 bytes


5. How to get the documentation of the numpy add function from the command line?¶
커맨드 라인에서 numpy 실행

6. Create a null vector of size 10 but the fifth value which is 1¶
5번째 값은 1인 10개의 null vector 생성
인덱스는 0부터 시작하므로 5번째는 [4]

In [17]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49¶
10 부터 49까지 범위의 vector 생성

In [18]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)¶
vector 역순 (첫번째 요소가 마지막이 됨)

In [19]:
z = np.arange(50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9. Create a 3x3 matrix with values ranging from 0 to 8¶
0 부터 8까지의 3x3 matrix 생성

In [26]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]¶
[1,2,0,0,4,0] 요소에서 0 이 아닌 인덱스 찾기

In [32]:
nz = np.nonzero([1,2,0,0,4,0])
print("nz:",nz)

nz2 = np.nonzero([1,4,5,6,7,0,2,0,0,0])
print("nz2:",nz2)

nz: (array([0, 1, 4], dtype=int64),)
nz2: (array([0, 1, 2, 3, 4, 6], dtype=int64),)


11. Create a 3x3 identity matrix¶
3x3 identity matrix 생성

In [38]:
z = np.eye(5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

12. Create a 3x3x3 array with random values¶
무작위 값으로 3x3x3 배열 생성

In [44]:
z = np.random.random((3,3,3))
print(z)

[[[0.25828324 0.68943787 0.58501861]
  [0.02442731 0.6342701  0.31594839]
  [0.08690962 0.53227024 0.60535259]]

 [[0.25971356 0.56052958 0.26417201]
  [0.49814828 0.96747206 0.85007796]
  [0.11920824 0.24942229 0.21254194]]

 [[0.59990843 0.88703448 0.4161118 ]
  [0.33825209 0.24072692 0.99031023]
  [0.50984905 0.79354657 0.85509502]]]


13. Create a 10x10 array with random values and find the minimum and maximum values¶
무작위 값으로 10x10 배열 생성하고 최소값, 최대값 찾기

In [50]:
z = np.random.random((10,10))
Zmin, Zmax = z.min(), z.max()
print(Zmin, Zmax)

0.01338857755544276 0.9992631597856121


14. Create a random vector of size 30 and find the mean value¶
평균값 구하기

In [51]:
z = np.random.random(30)
zmean = z.mean()
print(zmean)

0.37661431383447064


15. Create a 2d array with 1 on the border and 0 inside¶
2차원 배열 생성 (10 x 10)
전체값으로 1으로 채운다
내부만 0으로 채운다

In [52]:
z = np.ones((10,10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [58]:
z = np.ones((5,5))
print(z)
print()

# 테두리를 0으로 감싸기
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression?¶

In [59]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal¶

In [61]:
np.arange(4)

array([0, 1, 2, 3])

In [72]:
# k: 시작 위치
# diag: 대각 행렬
z = np.diag(1+np.arange(4), k= -1)
z

<class 'numpy.ndarray'>


19. Create a 8x8 matrix and fill it with a checkerboard pattern¶
checkerboard 패턴으로 1을 채운다

In [109]:
z = np.zeros((8,8), dtype= int)
# z[행, 열]
# z[ start : end : step ]
z[::2, 1::2] = 1
z[1::2, ::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?¶
(6,7,8) 형태 배열에서
100번째 요소의 인덱스를 구한다

In [111]:
# 100번째 요소의 index위치를 반환한다.
# (6, 7, 8) = 6개의 7행 8열
np.unravel_index(99, (6,7,8))

(1, 5, 3)

21. Create a checkerboard 8x8 matrix using the tile function¶
(2,2)단위 메트릭스를 만들고
단위 메트릭스를 (4,4)로 만든다.

In [116]:
# 크기를 4배
a = np.array([[0,1], [1,0]])
print(a)
print()
z = np.tile(a, (4,4))
print(z)

[[0 1]
 [1 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix¶

In [129]:
# 정규화 시키기
#  - 정규화: 서로 다른값의 범위를 0 ~ 1사이의 값으로 맞춰주기
# std: 표준편차
z = np.random.random((5,5))
z = (z - np.mean(z) / (np.std(z)))
print(np.std(z))
print()
print(z)

0.27508897747330896

[[-1.36257659 -1.39820084 -1.42024251 -1.530507   -0.67253364]
 [-0.86500762 -1.21970681 -0.88873672 -1.0275227  -1.13565178]
 [-1.42387982 -1.57023985 -1.17861614 -1.54112124 -1.29448609]
 [-0.83988714 -0.98462483 -1.1358002  -0.85983045 -0.9154855 ]
 [-1.35776967 -0.59840871 -1.46182276 -0.99005028 -1.25763103]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)¶

In [21]:
color = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte, 1),
                 ("b", np.ubyte, 1),
                 ("a",np.ubyte, 1)
                 ])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-21-9319b7e03057>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [ ]:
np.dtype()

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)¶

In [134]:
# 행렬의 곱셈
z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)
print()
z_ = np.ones((5,3)) @ np.ones((3,2))
print(z_)
print()
print(np.ones((5,3)))
print()
print(np.ones((3,2)))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.¶
0부터 10까지 1차원 배열 생성
3부터 8까지 음수로 변경

In [136]:
z = np.arange(11)
print(z)
z[(3<=z) & (z<=8)] *= -1
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


26. What is the output of the following script?¶
sum 에서 2번째 파라미터는 시작값을 지정 (기본: 0)
np.sum에서 2번째 파라미터는 축을 지정
If axis is negative it counts from the last to the first axis.

In [40]:
print(sum(range(5), -1))
print(np.sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal?¶

In [45]:
Z = np.arange(11)

# Z**Z
print(Z @ Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)

385
[  0   1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


28. What are the result of the following expressions?¶

In [ ]:
print(np.array(0) / np.array(0))
print()
print(np.array(0) // np.array(0))
print()
print(np.array([np.nan]).astype(int).astype(float))

29. How to round away from zero a float array ?¶

In [51]:
Z = np.random.uniform(-10, +10, 10)
print(Z)
print()
print(np.copysign(np.ceil(np.abs(Z)),Z))

[ 2.2545551  -3.18408178 -1.07367994 -8.25920441 -3.88389116 -9.68874913
 -5.17253091 -5.52735458 -7.18183585  4.19085575]

[  3.  -4.  -2.  -9.  -4. -10.  -6.  -6.  -8.   5.]


30. How to find common values between two arrays?¶

In [52]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1, Z2))

31. How to ignore all numpy warnings (not recommended)?¶

In [54]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

<ipython-input-54-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

32. Is the following expressions true?¶

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

33. How to get the dates of yesterday, today and tomorrow?¶

In [58]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
today = np.datetime64('today', 'D')
print(today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2020-12-22
2020-12-23
2020-12-24


34. How to get all the dates corresponding to the month of July 2016

In [63]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?¶

In [62]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array using 5 different methods¶

In [60]:
Z = np.random.uniform(0,10,10)
print(Z)

[5.21222192 5.72654229 8.01365631 5.60589035 3.91936819 5.81655685
 0.82192561 0.22639878 6.8627682  8.22356011]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [61]:
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


38. Consider a generator function that generates 10 integers and use it to build an array¶

In [64]:
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded¶

In [65]:
print(np.linspace(0,1,11))
print()
print(np.linspace(0,1,11, endpoint=False))
print()
print(np.linspace(0,1,11, endpoint=False)[1:])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it¶

In [66]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.44619399 0.45394232 0.49055352 0.52966653 0.60765764 0.65247049
 0.74935667 0.82118939 0.91918449 0.91975001]
